### ISSUE TITLE
Remove Assumption on SCE Repository Locations

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/SCE-CLI#24]
Setting up the dev tool assumes all discord, Core-v4, Quasar (with #22) will be contained entirely in dev. We need to consider the use case where the user who is first using this tool is an existing contributor to SCE and not just a new one.

We can store repo paths like `SCE_COREV4_PATH` in the users `.bashrc` or whatever the Windows equivalent. That way we can change directories more effectively over what we [currently do](https://github.com/SCE-Development/dev/blob/1b924a41d2b67cd3c40c63537d99950c6422f8be/tools/sce_service_handler.py#L12).

## Option 1
When we are setting up this tool for the first time, ask the user if they wanna have a repo be cloned. If not, tell them to move said repo (e.g. core-v4) into this directory. This means the sce tool will only work if we have project as a subdirectory. Can we [do better](https://www.youtube.com/watch?v=h7ftsoSvKVM)?

## Option 2
When we are setting up this tool for the first time, ask the user if they wanna have a repo be cloned. If not, tell the user to go into a repos path from the terminal and do `sce init-path <repo>`, `<repo>` being `core-v4` `discord` or `quasar` for example.

### What if we specified a path already?
Do something like

```
Seems like you already specified a path for <repo>.
Overwrite it? [y/N]:
```

and if the user hits y then we update the variable mentioned at the top of this issue.
![image](https://user-images.githubusercontent.com/36345325/148495726-e1987504-0260-4ade-a05c-0b5fa517309d.png)

### Add some verification?
What if I try `sce init-path core-v4` from `~/Downloads`? Surely that's not core-v4. What if we add verification? This can be parsing package.json and checking the value of the name field (Core-v4's [package.json:2](https://github.com/SCE-Development/Core-v4/blame/46be341fda1fa9d42c51a42bb79fececdc7469b4/package.json#L2)).

**Comment by CCLDArjun** [comment]
I think a better way to do it would be to symlink it into this project's current repository. 

In the code, we can then imagine that the sce projects are in this tool's directory and leave the code that accesses the projects alone.

**Comment by evanugarte** [comment]
> I think a better way to do it would be to symlink it into this project's current repository.
> 
> In the code, we can then imagine that the sce projects are in this tool's directory and leave the code that accesses the projects alone.

![image](https://user-images.githubusercontent.com/36345325/156664361-12982fc5-7c49-4e76-84d0-d9025946a075.png)
