### ISSUE TITLE
Add script to upgrade node on Linux

### ISSUE THREAD

**Issue by crowbardispensingcore** [SCE-Development/SCE-CLI#35]
Currently, the version of Node in Ubuntu's default repository is outdated and not supported by npm. We can add script to detect the installed version and upgrade it via various methods (such as nvm).

**Comment by evanugarte** [comment]
We could manually install nvm if it's not installed and then use it to install change both node and npm.

An example of downlading a script to handle this is in [`Quasar/printer/Dockerfile:12`](https://github.com/SCE-Development/Quasar/blob/103aab08569d39e0daf81b0623c383b221ac7003/printer/Dockerfile#L12)
