### ISSUE TITLE
Refractor service_handler to better accommodate reading interrupt signal and stopping Docker container

### ISSUE THREAD

**Issue by crowbardispensingcore** [SCE-Development/SCE-CLI#37]
Currently, the way service_handler is implemented makes it difficult to enforce the order of services being run by `sce run -s {services}` command. It also makes it difficult to handle keyboard interruptions.

Suggestions:
use dictionaries to store services and enforce running order

**Comment by evanugarte** [comment]
One way would be through docker container live reloads ([stackoverflow](https://stackoverflow.com/a/61577792))

**Comment by evanugarte** [comment]
closing this due to #30, we run docker stuff in detached mode at the moment
